rules:
  indent:
    - warn
    - 2
    -
      SwitchCase: 1
  quotes:
    - warn
    - single
    -
      allowTemplateLiterals: true
  linebreak-style:
    - warn
    - unix
  semi:
    - warn
    - never
  no-console: 0
  comma-dangle:
    - error
    - always-multiline
  no-unused-vars:
    - warn
  no-debugger: 0
env:
  es6: true
  node: true
parserOptions:
  sourceType: module
extends: 'eslint:recommended'
