rules:
  indent:
    - 2
    - 2
    -
      SwitchCase: 1
  quotes:
    - 1
    - single
  linebreak-style:
    - 1
    - unix
  semi:
    - 1
    - never
  no-console: 0
env:
  es6: true
  node: true
parserOptions:
  sourceType: module
extends: 'eslint:recommended'
